version: "3.9"

services:
  backend:
    build: ./backend
    container_name: boblog_backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - ./.env:/app/.env 
    working_dir: /app
    command: go run main.go

  db:
    image: mysql:8.0
    container_name: boblog_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
