version: "3.9"

services:
  gateway:
    image: nginx:alpine
    container_name: boblog_gateway
    ports:
      - "80:80"  # expose ให้เข้าทุกอย่างผ่าน localhost
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: boblog_frontend
    expose:
      - "3000:3000"  # เปิดให้ NGINX เข้าถึงเท่านั้น
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "npm install && npm run dev"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: boblog_backend
    expose:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./backend:/app
    working_dir: /app
    command: go run main.go
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: boblog_db
    ports:
      - "3307:3306"  # ✅ สำหรับเชื่อมจาก host (ถ้าไม่จำเป็นสามารถลบได้)
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  db_data:
